spring:
  application:
    name: transactionservice
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transactions_db}
    username: ${DB_USER:username}
    password: ${DB_PASS:password}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
  main:
    allow-circular-references: true




  cloud:
    compatibility-verifier:
      enabled: false


fixer:
  api:
    key: 85ef2089fc68eb68f6319c7966457d86
